### ISSUE TITLE
allow template selection for tests with Litmus

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/email-template-guide#10]
Currently when running `npm run test` / `gulp litmus` all views are automatically selected for testing. I'd prefer to be able to select one or more views (templates) to test specifically. I imagine we could achieve this with `inquirer`, similar to the `gulp add_module` task. I suggest we prompt the user with a list of templates to test and either pre-check all non-underscored views, or no views, or remember the last selection made. So you would get something like:

_which templates would you like to submit to Litmus for testing?_
- [ ] _base-view
- [ ] _component-preview
- [ ] _guide-viewer
- [x] demo_fluid-layout
- [x] welcome

I would even argue to always exclude all underscored views (convention) and in that case always use the last selection made.

**Comment by jpsc** [comment]
Fixed with the merge of feat/email-sender to master
