### ISSUE TITLE
When using * it gets styled inline everywhere

### ISSUE THREAD

**Issue by celinekurpershoek** [voorhoede/email-template-guide#14]
The usage of:

`* {
box-sizing: border-box;
}`

`<html xmlns="http://www.w3.org/1999/xhtml" style="box-sizing: border-box;">`
    `<head style="box-sizing: border-box;">`
        `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" style="box-sizing: border-box;">`

**Comment by jpsc** [comment]
Like it was suppose to? When you add it like that on the CSS file its doing that also.
Is this and issue ?
