### ISSUE TITLE
When creating a new module add the correspondant include to less file on main less

### ISSUE THREAD

**Issue by jpsc** [voorhoede/email-template-guide#6]
When using `gulp create_module` to add a new view or component the guide, the new created less files is not included on the main less file. That makes it necessary to add it manually.

Would be ideal if that happen on the creation of the module.

**Comment by celinekurpershoek** [comment]
For a new view its now been taken care of in an other way; the less file will be compiled in the same folder and with nunjucks the css will be included in the html. This way `gulp-inline-css` can generate the inline styles. I don't know if its a good idea to do that with the components also or to add them to the `index.less`. Maybe we should first see how it works out this way?

**Comment by jpsc** [comment]
If it works for views its okay. Because when you create a component you can only add it to the view that you are going to use it.

This is closed then.
