### ISSUE TITLE
add a mailer (smtp) task

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/email-template-guide#9]
Besides Litmus a good way to test an email would be simply sending it to a real address. This can be done by a mailer (smtp) service. I would like this project to include a default mailer task that can send an email using a template to a real email address. For this a service like [NodeMailer](https://github.com/andris9/Nodemailer) or [Haraka](https://github.com/baudehlo/Haraka) could be used. It would be nice if you could specify which email to send rather than sending them all.

**Comment by jpsc** [comment]
Done.
